### ISSUE TITLE
running errors

### ISSUE THREAD

**Issue by xuzhang5788** [Bibyutatsu/proGENTRL#2] opened 2020-06-06 01:50 UTC
After I run this cell
model = gentrl.gentrlVAE(enc,
                         dec,
                         train_loader,
                         latent_descr,
                         feature_descr, load_model='./model/')

I got 
Cannot Load the Models: Enc Model not Found 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-443b0e2e4f19> in <module>
      3                          train_loader,
      4                          latent_descr,
----> 5                          feature_descr, load_model='./model/')

/mnt/SSD/projects/proGENTRL/progentrl/gen_vaelp.py in __init__(self, enc, dec, train_loader, latent_descr, feature_descr, tt_int, tt_type, beta, gamma, load_model)
     54 
     55         #Epoch Variables
---> 56         self.buf = None
     57 
     58     def get_elbo(self, x, y):

AttributeError: 'NoneType' object has no attribute 'buf'

**Comment by Bibyutatsu** [comment] 2020-06-06 10:49
Hi, 
It is because you do not have a model saved in `./model` folder. Please set `load_model=None` so that you can start a new model from scratch.
And if you have a previous GENTRL model saved and want to load it instead, set `load_model=/path/to/GENTRL/model/folder`.

**Comment by xuzhang5788** [comment] 2020-06-06 18:34
@Bibyutatsu 
Thank you so much. However, I tried, still have problems

When I load the model from previous GENTRL, I got
"Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU."

When I set load_model=None, and train, I got 
"GPUs requested but none are available"

I tested it with torch.cuda.is_available(), it is false.
If I use cpu trainer = Trainer(max_epochs=20, gpus=0), it works

I use torch.cuda.set_device(0) to set cuda GPU, I got
"cuda runtime error (30) : unknown error at /pytorch/torch/csrc/cuda/Module.cpp:33"

I am new for pytorch. I knew it is a gpu setting problem, but I don't know how to fix it. I only have one gpu and I trained previous GENTRL with my one gpu without any problems.

**Comment by Bibyutatsu** [comment] 2020-06-06 22:48
@xuzhang5788 
I think the pytorch version you are using is not compatible with your Cuda version so ` torch.cuda.is_available()` is `False`. 

Have you made a new environment to run proGENTRL? If yes, try to uninstall pytorch and install it again using `conda` i.e. `conda install pytorch torchvision cudatoolkit=<Cuda Version> -c pytorch`

And if you are using `Jupyterlab` or `Jupyter notebook` try to check which kernel you are using. (Please refer [this](https://github.com/Bibyutatsu/GENTRL#step-3--optional) for kernel-related issues)

I think it will again start running when your pytorch can start detecting cuda i.e. `torch.cuda.is_available()` is `True`

**Comment by xuzhang5788** [comment] 2020-06-07 01:09
@Bibyutatsu 
Thank you so much. 
I used the same virtual environment as original GENTRL. My cuda version is 10.1

I created a new virtual environment and followed your instruction step-by-step. When I do python3 setup.py install. I got "error: Could not find suitable distribution for Requirement.parse('pytorch-lightning==0.7.6joblib>=0.13.2')". 

Then I pip install pytorch-lightning, still got "No module named 'gentrl'. 

After I installed pytorch using conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
I still got torch.cuda.is_available() is False.

I ran original GENTRL using GPU without any problem.

**Comment by xuzhang5788** [comment] 2020-06-07 02:21
@Bibyutatsu 
I restarted my computer, reran your sample.jpynb at original GENTRL virtual enviornment, finally, I can connect my gpu. 

However, when I try to do section 3, trainer.fit(model), I got 
"expected backend CUDA and dtype Float but got backend CPU and dtype Float" no matter I use load_model=None or load_model='/path/to/GENTRL/model/folder'

Luckily, when I try the section 4, it worked well and can do sampling.

For the new virtual environment, it still didn't work whatever I tried to install libraries.

**Comment by Bibyutatsu** [comment] 2020-06-07 07:28
@xuzhang5788 
Okay thanks for informing, I think the setup.py is at fault here. I will try to create a detailed setup instruction or use a bash script. 

And as for section 3, `trainer.fit(model)` please check that the syntax above is  `trainer = Trainer(max_epochs=10, gpus=-1)`. If there is no `gpus` argument or `gpus=None` it will try to use `CPU` so just put `gpus=-1` or `gpus=1`.

Please try it and tell me whether it works or not.

**Comment by xuzhang5788** [comment] 2020-06-07 18:18
@Bibyutatsu 
in: trainer = Trainer(max_epochs=20, gpus=-1)
out: GPU available: True, used: True
      No environment variable for node rank defined. Set as 0.
      CUDA_VISIBLE_DEVICES: [0]


in: trainer.fit(model)  # Training the model
out:

   | Name                 | Type           | Params
----------------------------------------------------
0  | enc                  | RNNEncoder     | 888 K 
1  | enc.embs             | Embedding      | 7 K   
2  | enc.rnn              | GRU            | 789 K 
3  | enc.final_mlp        | Sequential     | 91 K  
4  | enc.final_mlp.0      | Linear         | 65 K  
5  | enc.final_mlp.1      | LeakyReLU      | 0     
6  | enc.final_mlp.2      | Linear         | 25 K  
7  | dec                  | DilConvDecoder | 596 K 
8  | dec.latent_fc        | Linear         | 6 K   
9  | dec.input_embeddings | Embedding      | 3 K   
10 | dec.logits_1x1_layer | Conv1d         | 3 K   
11 | dec.parameters       | ParameterList  | 596 K 
12 | lp                   | LP             | 1 M   
13 | lp.parameters        | ParameterList  | 1 M   

Epoch 1: 0%
100/31693 [00:22<1:58:52, 4.43it/s, elbo_loss=-1.56, kl=-219, log_p_y_by_z=-.226, log_p_z_by_y=-257, loss=-1.554, rec=-.6, v_num=3]

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-2c1f8bdbe31c> in <module>
----> 1 trainer.fit(model)  # Training the model

~/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloader, val_dataloaders)
    857 
    858         elif self.single_gpu:
--> 859             self.single_gpu_train(model)
    860 
    861         elif self.use_tpu:  # pragma: no-cover

~/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py in single_gpu_train(self, model)
    501             self.optimizers = optimizers
    502 
--> 503         self.run_pretrain_routine(model)
    504 
    505     def tpu_train(self, tpu_core_idx, model):

~/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py in run_pretrain_routine(self, model)
   1013 
   1014         # CORE TRAINING LOOP
-> 1015         self.train()
   1016 
   1017     def test(

~/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py in train(self)
    345                 # RUN TNG EPOCH
    346                 # -----------------
--> 347                 self.run_training_epoch()
    348 
    349                 # update LR schedulers

~/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py in run_training_epoch(self)
    417             # RUN TRAIN STEP
    418             # ---------------
--> 419             _outputs = self.run_training_batch(batch, batch_idx)
    420             batch_result, grad_norm_dic, batch_step_metrics, batch_output = _outputs
    421 

~/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py in run_training_batch(self, batch, batch_idx)
    595 
    596                 # calculate loss
--> 597                 loss, batch_output = optimizer_closure()
    598 
    599                 # check if loss or model weights are nan

~/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py in optimizer_closure()
    559                                                                     opt_idx, self.hiddens)
    560                         else:
--> 561                             output_dict = self.training_forward(split_batch, batch_idx, opt_idx, self.hiddens)
    562 
    563                         # format and reduce outputs accordingly

~/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py in training_forward(self, batch, batch_idx, opt_idx, hiddens)
    725             batch = self.transfer_batch_to_gpu(batch, gpu_id)
    726             args[0] = batch
--> 727             output = self.model.training_step(*args)
    728 
    729         # TPU support

/mnt/SSD/projects/proGENTRL/progentrl/gen_vaelp.py in training_step(self, batch, batch_idx)
    131                 to_reinit = False
    132 
--> 133         elbo, cur_stats = self.get_elbo(x_batch, y_batch)
    134         loss = -elbo
    135 

/mnt/SSD/projects/proGENTRL/progentrl/gen_vaelp.py in get_elbo(self, x, y)
     70 
     71         zy = torch.cat([latvar_samples, y], dim=1)
---> 72         log_p_zy = self.lp.log_prob(zy)
     73 
     74         y_to_marg = latent_dim * [True] + condition_dim * [False]

/mnt/SSD/projects/proGENTRL/progentrl/lp.py in log_prob(self, x, marg)
    177                                                        var, None,
    178                                                        perm_means[i],
--> 179                                                        perm_log_stds[i])
    180                 cond_core = core[None, :, :, :]
    181                 cond_core = cond_core * cur_contr_vect[:, :, None, None]

/mnt/SSD/projects/proGENTRL/progentrl/lp.py in __make_contr_vec(x, var, missed, means, log_stds)
    116             cur_means = means[None, :]
    117 
--> 118             contr_vect = (cur_vals - cur_means) / cur_stds
    119             contr_vect = torch.exp(-0.5 * (contr_vect ** 2))
    120             contr_vect = contr_vect / (sqrt(2 * pi) * cur_stds)

RuntimeError: expected backend CUDA and dtype Float but got backend CPU and dtype Float

**Comment by Bibyutatsu** [comment] 2020-06-07 23:43
@xuzhang5788 
I will try to recreate this error in my machine, if you can share a colab or kaggle version to create this error it will be very helpful because I am still unable to find this bug in my runtime.

**Comment by xuzhang5788** [comment] 2020-06-08 00:37
I used my own computer. I can attach jpynb file.

**Comment by Bibyutatsu** [comment] 2020-06-11 21:34
@xuzhang5788 ,
I am able to reproduce and correct those errors. Please check and get back to me in case of any issues.

**Comment by xuzhang5788** [comment] 2020-06-11 22:39
@Bibyutatsu 
I am sorry it still doesn't work. Now I used original gentrl env, I can not connect with rdkit_kernel. So I used Python3 as the kernel. Then I received above errors.

When I tried to install new env following your instruction, I can connect rdkit_kernel, but I got torch.cuda.is_available() is False. Even though I restarted my computer. 

If I change kernel to python3, I got "No module named 'torch'". It is installed outside the jupyter notebook.

**Comment by Bibyutatsu** [comment] 2020-06-12 06:58
@xuzhang5788,
Please try once again after taking a pull. I am successfully able to run the whole training.

For `torch.cuda.is_available() = False` error, try this:
```
pip uninstall torch
conda install pytorch torchvision cudatoolkit=<cuda_version> -c pytorch
```

**Comment by xuzhang5788** [comment] 2020-06-14 18:39
@Bibyutatsu 
I reload your repo and run the training. This time, for pre-training, it works. It took 40 hours for 20 epochs. Compared to original one, it only took 22 hours. I am sure that I was using GPU.

However, when I tried to train the second part, reinforcement learning training, I got "The kernel appears to have died. It will restart automatically.",  no matter I used python3 or ridkit as my kernel.

**Comment by Bibyutatsu** [comment] 2020-06-15 17:41
Hi,
Yeah, in original gentrl the total number of epochs were 10, as you can see [here](https://github.com/Bibyutatsu/GENTRL/blob/813821d40f32600b4964940925dc0e254a96dedc/gentrl/gentrl.py#L120). But in our case it is 20. So it has taken double the time.

The kernel must be dying due to memory issues. Please check your RAM and GPUafter you load the model because in my PC it is running fine. You can refer this [Colab notebook](https://colab.research.google.com/drive/1E8hxHu-iSW0W2Y8hhpCEM_2TE5m6vy-9?usp=sharing) where I have systematically implemented it.

**Comment by xuzhang5788** [comment] 2020-06-15 18:10
Thank you for your reply. 
When I use your virtual env., I got above errors. But I back to the original GENTRL env, it worked. I don't know what the difference between these two envs. 

In addition, may I ask you favour?  For my application, I want to generate molecules from a parent molecule, not randomly sample from the latent space. The generated molecules are new molecules but still have the similar structure, better property and so on. Would you like to write some codes to implement this? I think many people need this function. Also, you should add a part in your example.ipynb about how to load the saved model and do the thing. Maybe because I am new for pytorch, so I need this part. Many thanks.

**Comment by Bibyutatsu** [comment] 2020-06-23 06:07
@xuzhang5788 
Yeah sure I will start working on it. Will inform you once I am able to do that. 

Closing this issue. Thanks for using it.

**Closed as completed by Bibyutatsu** 2020-06-23 06:07 UTC
Labels: good first issue
